### ISSUE TITLE
Calibration for K2182A

### ISSUE THREAD

**Issue by tin-** [marcoreps/keithley-2182a#1]
Thanks for report upload, nice to see good old Keithley 262 being used properly in the procedure. 
I'm interested to see your experiments with 2182A, they are quite capable meters for low resistance and low voltage measurements.

**Comment by marcoreps** [comment]
Hey TiN long time no see! Got any opinions regarding 2182A vs 34420A? At the moment I like the HP flavor a little bit better

**Comment by tin-** [comment]
> Hey TiN long time no see! Got any opinions regarding 2182A vs 34420A? At the moment I like the HP flavor a little bit better

34420A is more versatile instrument, since it provides you with resistance functionality. It's also little bit friendlier and easier to repair since schematics is available, unlike the Keithley. Performance-wise they are very close with noise ~30 nVpk-pk at best settings. I have 2182A because it was cheap ($200) and I am Keithley fanboi.
